### ISSUE TITLE
AUR Package

### ISSUE THREAD

**Issue by ghost** [cbrnix/Newaita-reborn#2]
What do you think about creating an AUR package for installing the icons? For me it's much better than having to update the icons manually.

**Comment by cbrnix** [comment]
To be honest ... I've never done this. And I can’t diffuse my strength - there is too much to do, and there is still Flatery. If you have such an opportunity - do it. I will only be glad.
I agree that updating through the AUR is much more convenient.

**Comment by ghost** [comment]
@cbrnix  I'm really trying to create the AUR package for you, but because of the number of icons that this repository has, the package installation time is very high (45 minutes on my computer). Would it be a problem if I only included the `Newaita-reborn` and `Newaita-reborn-dark` icons taking out the different colored icons?

**Comment by cbrnix** [comment]
I plan to replace the duplicate directories, leaving only links to the main theme (like Flatery). This is in perspective. So, if it's more convenient for you, leave the base. Later it will be possible to add 
Thank you for participating. Unfortunately, I don't always have enough time for hobbies.

**Comment by cahian** [comment]
> leave the base

What do you mean to leave the base? :upside_down_face:

**Comment by cbrnix** [comment]
@cahian 
I changed the configuration. Now there are only symlinks in variants. This should shorten the preparation time and simplify the task.

**Comment by ghost** [comment]
Thanks, now installation time is approximately 1 minute on my computer. I've already published the package for you:
https://aur.archlinux.org/packages/newaita-reborn-icons-git/

**Comment by ghost** [comment]
The only thing left is to add the package to the `README.md`.

**Comment by cbrnix** [comment]
Added. Thanks for your endeavors
