### ISSUE TITLE
Please add icons for jetbrains series apps  and "visual studio code"

### ISSUE THREAD

**Issue by teddingdev** [cbrnix/Newaita-reborn#4]
### jetbrains series
https://www.jetbrains.com/idea/
https://www.jetbrains.com/webstorm/
https://www.jetbrains.com/rider/
https://www.jetbrains.com/clion/
https://www.jetbrains.com/pycharm/
https://www.jetbrains.com/phpstorm/
https://www.jetbrains.com/ruby/
https://www.jetbrains.com/go/
https://www.jetbrains.com/datagrip/
### visual studio code
https://code.visualstudio.com/
### postman
https://www.postman.com/
### tencent wechat 
https://weixin.qq.com/

**Comment by cbrnix** [comment]
The jetbrains series was missing a few links and a couple of icons. Otherwise, all the icons were already there. Visualstudio is already there. There might be a problem in .desktop
I also added
wewechat, wechat, deepin.com.wechat, appimagekit-wewechat, postman, com.getpostman.Postman
